//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.MuonSaches = new HashSet<MuonSach>();
            this.TraSaches = new HashSet<TraSach>();
        }
    
        public string Mã_sách { get; set; }
        public string Tên_sách { get; set; }
        public string Năm_xuất_bản { get; set; }
        public string Nhà_xuất_bản { get; set; }
        public Nullable<int> Số_lượng { get; set; }
        public string Tác_giả { get; set; }
        public string Loại { get; set; }
        public Nullable<int> Giá { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraSach> TraSaches { get; set; }
    }
}
